language: cpp
git:
    quiet: true
    depth: false

compiler: g++
dist: trusty
sudo: required
os: linux
env:
    matrix:
    - PYVERSION=python3.4
    - PYVERSION=python3.5
    - PYVERSION=python3.6

env: CUDA=9.0.176
before_install:
    - sudo apt-get update
    - sudo apt-get install python3-dev
    - sudo apt-get install python3-pip
    - sudo python3 -m pip install pybind11

script: make
